# Generated by Django 5.2.14 on 2026-06-27 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('national_or_company_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('credit_score', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Issuer Profile',
                'verbose_name_plural': 'Issuer Profiles',
            },
        ),
        migrations.CreateModel(
            name='ChequeListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('cheque_serial_number', models.CharField(max_length=50)),
                ('face_amount', models.DecimalField(decimal_places=0, max_digits=15)),
                ('due_date', models.DateField()),
                ('issuer_type', models.CharField(choices=[('legal', 'Legal'), ('natural', 'Natural')], max_length=10)),
                ('issuer_name', models.CharField(max_length=255)),
                ('issuer_national_id', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('suggested_discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('risk_tier', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, null=True)),
                ('status', models.CharField(choices=[('pending_moderation', 'Pending Moderation'), ('published', 'Published'), ('rejected', 'Rejected'), ('matched', 'Matched'), ('expired', 'Expired'), ('withdrawn', 'Withdrawn'), ('settled_off_platform', 'Settled Off Platform')], default='pending_moderation', max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_listings', to=settings.AUTH_USER_MODEL)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheque_listings', to='checks.issuerprofile')),
            ],
            options={
                'verbose_name': 'Cheque Listing',
                'verbose_name_plural': 'Cheque Listings',
                'indexes': [models.Index(fields=['status', 'due_date'], name='checks_cheq_status_9aa6da_idx'), models.Index(fields=['owner', 'status'], name='checks_cheq_owner_i_72604a_idx')],
                'constraints': [models.UniqueConstraint(fields=('issuer', 'bank_name', 'cheque_serial_number'), name='unique_cheque_per_issuer_per_bank')],
            },
        ),
    ]
