# Generated by Django 5.2.14 on 2026-06-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chequelisting",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="chequelisting",
            name="rejection_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MOD_101", "Incomplete information"),
                    ("MOD_102", "Poor quality image"),
                    ("MOD_103", "Invalid cheque"),
                    ("MOD_104", "Duplicate listing"),
                    ("MOD_105", "Risk too high"),
                    ("MOD_106", "Other"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chequelisting",
            name="resubmit_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
