# Generated by Django 5.2.14 on 2026-08-06 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_chequelisting_rejection_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chequelisting',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cheque Listing', 'verbose_name_plural': 'Cheque Listings'},
        ),
        migrations.AlterModelOptions(
            name='issuerprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Issuer Profile', 'verbose_name_plural': 'Issuer Profiles'},
        ),
        migrations.AddField(
            model_name='issuerprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_issuer_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
