# Generated by Django 5.2.14 on 2026-08-19 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
        ('checks', '0003_v1_mvp_gates'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequelisting',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cheque_listings', to='banks.bank'),
        ),
    ]
