# Generated by Django 5.2.14 on 2026-08-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureflag',
            options={'ordering': ['key'], 'verbose_name': 'Feature Flag', 'verbose_name_plural': 'Feature Flags'},
        ),
    ]
