# Generated by Django 5.2.14 on 2026-06-28 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("checks", "0002_chequelisting_rejection_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModerationDecision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[("approved", "Approved"), ("rejected", "Rejected")],
                        max_length=20,
                    ),
                ),
                (
                    "rejection_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MOD_101", "Incomplete information"),
                            ("MOD_102", "Poor quality image"),
                            ("MOD_103", "Invalid cheque"),
                            ("MOD_104", "Duplicate listing"),
                            ("MOD_105", "Risk too high"),
                            ("MOD_106", "Other"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("rejection_note", models.TextField(blank=True, default="")),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_decisions",
                        to="checks.chequelisting",
                    ),
                ),
                (
                    "moderator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderation Decision",
                "verbose_name_plural": "Moderation Decisions",
                "indexes": [
                    models.Index(
                        fields=["listing", "-created_at"],
                        name="moderation__listing_8f3c0e_idx",
                    ),
                ],
            },
        ),
    ]
