# Generated by Django 5.2.14 on 2026-08-19 12:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('aliases', models.JSONField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='banks/logos/')),
                ('brand_color_light', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Brand color must be #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('brand_color_dark', models.CharField(max_length=7, validators=[django.core.validators.RegexValidator(message='Brand color must be #RRGGBB.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Bank',
                'verbose_name_plural': 'Banks',
                'ordering': ['display_name'],
            },
        ),
    ]
