# Generated by Django 5.2.14 on 2026-06-28 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('checks', '0002_chequelisting_rejection_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled'), ('off_platform_confirmed', 'Off Platform Confirmed'), ('settled', 'Settled')], default='pending', max_length=30)),
                ('settlement_type', models.CharField(choices=[('off_platform', 'Off Platform'), ('escrow', 'Escrow')], default='off_platform', max_length=20)),
                ('final_discount_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('terms', models.TextField(blank=True, default='')),
                ('message', models.TextField(blank=True, default='')),
                ('check_holder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holder_matches', to=settings.AUTH_USER_MODEL)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investor_matches', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='checks.chequelisting')),
            ],
        ),
        migrations.CreateModel(
            name='OffPlatformSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmation_code', models.CharField(max_length=100)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('settlement_notes', models.TextField(blank=True, default='')),
                ('confirmed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_confirmations', to=settings.AUTH_USER_MODEL)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='off_platform_settlement', to='matching.match')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SettlementPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('port_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settlement_port', to='matching.match')),
            ],
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['status'], name='matching_ma_status_8042fa_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['check_holder'], name='matching_ma_check_h_4b8b18_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['investor'], name='matching_ma_investo_30677b_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['created_at'], name='matching_ma_created_9824e1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('listing', 'check_holder')},
        ),
        migrations.AlterUniqueTogether(
            name='settlementport',
            unique_together={('match', 'port_number')},
        ),
    ]
