# Generated by Django 5.2.14 on 2026-06-28 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_chequelisting_rejection_fields'),
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='match',
            name='matching_ma_check_h_4b8b18_idx',
        ),
        migrations.RemoveIndex(
            model_name='match',
            name='matching_ma_investo_30677b_idx',
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='match',
            name='settlement_type',
            field=models.CharField(choices=[('off_platform', 'Off Platform'), ('escrow', 'Escrow'), ('principal_ledger', 'Principal Ledger')], default='off_platform', max_length=20),
        ),
        migrations.AlterField(
            model_name='offplatformsettlement',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settlement_confirmations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='offplatformsettlement',
            unique_together={('match',)},
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['check_holder', 'status'], name='matching_ma_check_h_7b9a50_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['investor', 'status'], name='matching_ma_investo_c7eed6_idx'),
        ),
    ]
