# Generated by Django 5.2.14 on 2026-08-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_remove_match_matching_ma_check_h_4b8b18_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-created_at']},
        ),
    ]
