# Generated by Django 5.2.14 on 2026-06-24 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_phone_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('check_holder', 'Check Holder'), ('investor', 'Investor'), ('moderator', 'Moderator'), ('admin', 'Admin')], default='check_holder', max_length=20, verbose_name='Role'),
        ),
    ]
