# Generated by Django 5.2.14 on 2026-08-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_alter_profile_role_verification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Verification', 'verbose_name_plural': 'Verifications'},
        ),
    ]
