# Generated by Django 5.2.14 on 2026-08-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_v1_mvp_gates'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(choices=[('natural', 'Natural Person'), ('legal', 'Legal Entity')], db_index=True, default='natural', max_length=20),
        ),
        migrations.AlterField(
            model_name='verification',
            name='national_id',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
